
package org.openecomp.ncomp.servers.cdap.logging;

import com.att.eelf.i18n.EELFResourceManager;
import org.openecomp.logger.EcompMessageEnum;

public enum CdapClusterMessageEnum implements EcompMessageEnum {

  dummy,
  REQUEST_FAILED_createNamespace,
  REQUEST_FAILED_deleteNamespace,
  REQUEST_FAILED_deployApp,
  REQUEST_FAILED_loadArtifact,
  REQUEST_FAILED_loadArtifactWithConfig,
  REQUEST_FAILED_deleteArtifact,
  REQUEST_FAILED_startFlow,
  REQUEST_FAILED_startWorker,
  REQUEST_FAILED_startService,
  REQUEST_FAILED_startApp,
  REQUEST_FAILED_stopApp,
  REQUEST_FAILED_deleteApp,
  REQUEST_FAILED_loadPreferencesApp,
  REQUEST_FAILED_loadPreferencesFlow,
  REQUEST_FAILED_loadPreferencesNameSpace,
  REQUEST_FAILED_setPreferencesApp,
  REQUEST_FAILED_setPreferencesFlow,
  REQUEST_FAILED_setPreferencesWorker,
  REQUEST_FAILED_setPreferencesService,
  REQUEST_FAILED_setPreferencesNameSpace,
  REQUEST_FAILED_setFlowRunTimeArgs,
  REQUEST_FAILED_setFlowletInstances,
  REQUEST_FAILED_stopFlow,
  REQUEST_FAILED_stopWorker,
  REQUEST_FAILED_stopService,
  REQUEST_FAILED_truncateDataSet,
  REQUEST_FAILED_deleteDataset,
  REQUEST_FAILED_createStream,
  REQUEST_FAILED_deleteStream,
  REQUEST_FAILED_getStreamEvents,
  REQUEST_FAILED_getStreamStats,
  REQUEST_FAILED_sendEventToStream,
  REQUEST_FAILED_trucateStream,
  REQUEST_FAILED_setStreamProperties,
  REQUEST_FAILED_restartApp,
  REQUEST_FAILED_createApp,
  REQUEST_FAILED_createAppWithConfig,
  REQUEST_FAILED_setDatasetProperties,
  REQUEST_FAILED_setStreamTTL,
  REQUEST_FAILED_suspendSchedule,
  REQUEST_FAILED_resumeSchedule,
  REQUEST_FAILED_poll,
  REMOTE_CALL_FAILED_createNamespace,
  REMOTE_CALL_FAILED_deleteNamespace,
  REMOTE_CALL_FAILED_deployApp,
  REMOTE_CALL_FAILED_loadArtifact,
  REMOTE_CALL_FAILED_loadArtifactWithConfig,
  REMOTE_CALL_FAILED_deleteArtifact,
  REMOTE_CALL_FAILED_startFlow,
  REMOTE_CALL_FAILED_startWorker,
  REMOTE_CALL_FAILED_startService,
  REMOTE_CALL_FAILED_startApp,
  REMOTE_CALL_FAILED_stopApp,
  REMOTE_CALL_FAILED_deleteApp,
  REMOTE_CALL_FAILED_loadPreferencesApp,
  REMOTE_CALL_FAILED_loadPreferencesFlow,
  REMOTE_CALL_FAILED_loadPreferencesNameSpace,
  REMOTE_CALL_FAILED_setPreferencesApp,
  REMOTE_CALL_FAILED_setPreferencesFlow,
  REMOTE_CALL_FAILED_setPreferencesWorker,
  REMOTE_CALL_FAILED_setPreferencesService,
  REMOTE_CALL_FAILED_setPreferencesNameSpace,
  REMOTE_CALL_FAILED_setFlowRunTimeArgs,
  REMOTE_CALL_FAILED_setFlowletInstances,
  REMOTE_CALL_FAILED_stopFlow,
  REMOTE_CALL_FAILED_stopWorker,
  REMOTE_CALL_FAILED_stopService,
  REMOTE_CALL_FAILED_truncateDataSet,
  REMOTE_CALL_FAILED_deleteDataset,
  REMOTE_CALL_FAILED_createStream,
  REMOTE_CALL_FAILED_deleteStream,
  REMOTE_CALL_FAILED_getStreamEvents,
  REMOTE_CALL_FAILED_getStreamStats,
  REMOTE_CALL_FAILED_sendEventToStream,
  REMOTE_CALL_FAILED_trucateStream,
  REMOTE_CALL_FAILED_setStreamProperties,
  REMOTE_CALL_FAILED_restartApp,
  REMOTE_CALL_FAILED_createApp,
  REMOTE_CALL_FAILED_createAppWithConfig,
  REMOTE_CALL_FAILED_setDatasetProperties,
  REMOTE_CALL_FAILED_setStreamTTL,
  REMOTE_CALL_FAILED_suspendSchedule,
  REMOTE_CALL_FAILED_resumeSchedule,
  REMOTE_CALL_FAILED_poll;

	static {
		EELFResourceManager.loadMessageBundle("org/openecomp/ncomp/servers/cdap/logging/CdapCluster");
	}
}
