
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit but extend this class as needed
package org.openecomp.ncomp.servers.cdap;


import org.apache.log4j.Logger;
import org.eclipse.emf.common.util.EList;

import org.openecomp.ncomp.sirius.manager.console.Console;
import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.ManagementServerError;

    

import org.openecomp.ncomp.servers.cdap.gui.CdapGuiClientApiConsole;   


public class CdapCdapAdaptorConsole extends Console {
	public static final Logger logger = Logger.getLogger(CdapCdapAdaptorConsole.class);
    protected CdapCdapAdaptorClient controller;
    
    
        CdapCdapClusterConsole cluster;       
        CdapGuiClientApiConsole gui;   


    public CdapCdapAdaptorConsole(String filename, String name) {
            super(filename, name);
            controller = new CdapCdapAdaptorClient(filename,name);
            client = controller.client;
    
            cluster = new  CdapCdapClusterConsole(filename,name);       
            gui = new  CdapGuiClientApiConsole(filename,name);   
    }
    
	public CdapCdapAdaptorConsole(AbstractClient c) {
        controller = new CdapCdapAdaptorClient(c);
        client = controller.client;
    }


}
