
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.ncomp.servers.cdap;

import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.HighAvailabilityClient;
import org.openecomp.ncomp.sirius.manager.GenericHttpClient;

import org.apache.log4j.Logger;

import org.openecomp.logger.EcompLogger;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;

import org.openecomp.ncomp.cdap.impl.CdapClusterImpl;
import org.openecomp.ncomp.cdap.CdapPackage;
import org.openecomp.ncomp.servers.cdap.logging.CdapClusterOperationEnum;
import org.openecomp.ncomp.servers.cdap.logging.CdapClusterMessageEnum;


import org.openecomp.ncomp.servers.cdap.CdapCdapAdaptor; 



 
@SuppressWarnings("unchecked")
public class CdapCdapClusterClient extends CdapClusterImpl {
	public static final Logger logger = Logger.getLogger(CdapCdapClusterClient.class);
	static final EcompLogger ecomplogger = EcompLogger.getEcompLogger();
	public AbstractClient client;

	public CdapCdapClusterClient(String file, String name) {
		CdapCdapAdaptor.ecoreSetup(); 
		client = new GenericHttpClient(file,name);
		client.add("/cluster", this);
	}

	public CdapCdapClusterClient(String file, String name1, String name2) {
		HighAvailabilityClient client1 = new HighAvailabilityClient(file,name1,name2);
		client = client1.all; // requests should be forwarded to all.
		client.add("/cluster", this);
	}
	
	public CdapCdapClusterClient(AbstractClient c) {
		client = c;
		client.add("/resources", this);
	}



	
	public void poll(String path) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_poll);
		
		try {
		  client.operationPath(path, c, "poll", null);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_poll, e.toString());
			throw new RuntimeException("remote call failed:  poll", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	
	public java.lang.String createNamespace(String path, java.lang.String namespace) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_createNamespace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "createNamespace", null, namespace);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_createNamespace, e.toString());
			throw new RuntimeException("remote call failed:  createNamespace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String deleteNamespace(String path, java.lang.String namespace) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_deleteNamespace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "deleteNamespace", null, namespace);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_deleteNamespace, e.toString());
			throw new RuntimeException("remote call failed:  deleteNamespace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String deployApp(String path, java.lang.String namespace, java.lang.String jarfile) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_deployApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "deployApp", null, namespace,jarfile);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_deployApp, e.toString());
			throw new RuntimeException("remote call failed:  deployApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String loadArtifact(String path, java.lang.String namespace, java.lang.String artifactName, java.lang.String jarfile, java.lang.String version) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_loadArtifact);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "loadArtifact", null, namespace,artifactName,jarfile,version);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_loadArtifact, e.toString());
			throw new RuntimeException("remote call failed:  loadArtifact", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String deleteArtifact(String path, java.lang.String namespace, java.lang.String artifactName, java.lang.String artifactVersion) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_deleteArtifact);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "deleteArtifact", null, namespace,artifactName,artifactVersion);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_deleteArtifact, e.toString());
			throw new RuntimeException("remote call failed:  deleteArtifact", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String startFlow(String path, java.lang.String namespace, java.lang.String appName, java.lang.String flowId, java.lang.String extraArgs) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_startFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "startFlow", null, namespace,appName,flowId,extraArgs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_startFlow, e.toString());
			throw new RuntimeException("remote call failed:  startFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String startWorker(String path, java.lang.String namespace, java.lang.String appName, java.lang.String workerId, java.lang.String extraArgs) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_startWorker);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "startWorker", null, namespace,appName,workerId,extraArgs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_startWorker, e.toString());
			throw new RuntimeException("remote call failed:  startWorker", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String startService(String path, java.lang.String namespace, java.lang.String appName, java.lang.String serviceId, java.lang.String extraArgs) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_startService);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "startService", null, namespace,appName,serviceId,extraArgs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_startService, e.toString());
			throw new RuntimeException("remote call failed:  startService", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String startApp(String path, java.lang.String namespace, java.lang.String appName) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_startApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "startApp", null, namespace,appName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_startApp, e.toString());
			throw new RuntimeException("remote call failed:  startApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String stopApp(String path, java.lang.String namespace, java.lang.String appName) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_stopApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "stopApp", null, namespace,appName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_stopApp, e.toString());
			throw new RuntimeException("remote call failed:  stopApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String deleteApp(String path, java.lang.String namespace, java.lang.String appName) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_deleteApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "deleteApp", null, namespace,appName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_deleteApp, e.toString());
			throw new RuntimeException("remote call failed:  deleteApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String loadPreferencesApp(String path, java.lang.String namespace, java.lang.String prefsFile, java.lang.String appId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_loadPreferencesApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "loadPreferencesApp", null, namespace,prefsFile,appId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_loadPreferencesApp, e.toString());
			throw new RuntimeException("remote call failed:  loadPreferencesApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String loadPreferencesFlow(String path, java.lang.String namespace, java.lang.String prefsFile, java.lang.String appId, java.lang.String flowId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_loadPreferencesFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "loadPreferencesFlow", null, namespace,prefsFile,appId,flowId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_loadPreferencesFlow, e.toString());
			throw new RuntimeException("remote call failed:  loadPreferencesFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String loadPreferencesNameSpace(String path, java.lang.String namespace, java.lang.String prefsFile) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_loadPreferencesNameSpace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "loadPreferencesNameSpace", null, namespace,prefsFile);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_loadPreferencesNameSpace, e.toString());
			throw new RuntimeException("remote call failed:  loadPreferencesNameSpace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setPreferencesApp(String path, java.lang.String namespace, java.lang.String prefsString, java.lang.String appId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setPreferencesApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setPreferencesApp", null, namespace,prefsString,appId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setPreferencesApp, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setPreferencesFlow(String path, java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String flowId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setPreferencesFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setPreferencesFlow", null, namespace,prefsString,appId,flowId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setPreferencesFlow, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setPreferencesWorker(String path, java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String workerId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setPreferencesWorker);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setPreferencesWorker", null, namespace,prefsString,appId,workerId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setPreferencesWorker, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesWorker", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setPreferencesService(String path, java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String serviceId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setPreferencesService);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setPreferencesService", null, namespace,prefsString,appId,serviceId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setPreferencesService, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesService", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setPreferencesNameSpace(String path, java.lang.String namespace, java.lang.String prefsString) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setPreferencesNameSpace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setPreferencesNameSpace", null, namespace,prefsString);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setPreferencesNameSpace, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesNameSpace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setFlowRunTimeArgs(String path, java.lang.String namespace, java.lang.String appId, java.lang.String flowId, java.lang.String args) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setFlowRunTimeArgs);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setFlowRunTimeArgs", null, namespace,appId,flowId,args);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setFlowRunTimeArgs, e.toString());
			throw new RuntimeException("remote call failed:  setFlowRunTimeArgs", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setFlowletInstances(String path, java.lang.String namespace, java.lang.String appId, java.lang.String flowId, java.lang.String flowletId, int nInstances) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setFlowletInstances);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setFlowletInstances", null, namespace,appId,flowId,flowletId,nInstances);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setFlowletInstances, e.toString());
			throw new RuntimeException("remote call failed:  setFlowletInstances", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String stopFlow(String path, java.lang.String namespace, java.lang.String appId, java.lang.String flowId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_stopFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "stopFlow", null, namespace,appId,flowId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_stopFlow, e.toString());
			throw new RuntimeException("remote call failed:  stopFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String stopWorker(String path, java.lang.String namespace, java.lang.String appId, java.lang.String workerId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_stopWorker);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "stopWorker", null, namespace,appId,workerId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_stopWorker, e.toString());
			throw new RuntimeException("remote call failed:  stopWorker", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String stopService(String path, java.lang.String namespace, java.lang.String appId, java.lang.String serviceId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_stopService);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "stopService", null, namespace,appId,serviceId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_stopService, e.toString());
			throw new RuntimeException("remote call failed:  stopService", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String truncateDataSet(String path, java.lang.String namespace, java.lang.String datasetName) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_truncateDataSet);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "truncateDataSet", null, namespace,datasetName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_truncateDataSet, e.toString());
			throw new RuntimeException("remote call failed:  truncateDataSet", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String deleteDataset(String path, java.lang.String namespace, java.lang.String datasetName) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_deleteDataset);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "deleteDataset", null, namespace,datasetName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_deleteDataset, e.toString());
			throw new RuntimeException("remote call failed:  deleteDataset", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String createStream(String path, java.lang.String namespace, java.lang.String newStreamId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_createStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "createStream", null, namespace,newStreamId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_createStream, e.toString());
			throw new RuntimeException("remote call failed:  createStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String deleteStream(String path, java.lang.String namespace, java.lang.String streamId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_deleteStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "deleteStream", null, namespace,streamId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_deleteStream, e.toString());
			throw new RuntimeException("remote call failed:  deleteStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public EList<java.lang.String> getStreamEvents(String path, java.lang.String namespace, java.lang.String streamId, java.lang.String startTime, java.lang.String endTime, int limit) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_getStreamEvents);
		EList<java.lang.String> res;
		try {
		  res = (EList<java.lang.String>) client.operationPath(path, c, "getStreamEvents", null, namespace,streamId,startTime,endTime,limit);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_getStreamEvents, e.toString());
			throw new RuntimeException("remote call failed:  getStreamEvents", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public EList<java.lang.String> getStreamStats(String path, java.lang.String namespace, java.lang.String streamId, java.lang.String startTime, java.lang.String endTime, int limit) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_getStreamStats);
		EList<java.lang.String> res;
		try {
		  res = (EList<java.lang.String>) client.operationPath(path, c, "getStreamStats", null, namespace,streamId,startTime,endTime,limit);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_getStreamStats, e.toString());
			throw new RuntimeException("remote call failed:  getStreamStats", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String sendEventToStream(String path, java.lang.String namespace, java.lang.String streamId, java.lang.String event) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_sendEventToStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "sendEventToStream", null, namespace,streamId,event);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_sendEventToStream, e.toString());
			throw new RuntimeException("remote call failed:  sendEventToStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String trucateStream(String path, java.lang.String namespace, java.lang.String streamId) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_trucateStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "trucateStream", null, namespace,streamId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_trucateStream, e.toString());
			throw new RuntimeException("remote call failed:  trucateStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setStreamProperties(String path, java.lang.String namespace, java.lang.String streamId, java.lang.String propsFile) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setStreamProperties);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setStreamProperties", null, namespace,streamId,propsFile);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setStreamProperties, e.toString());
			throw new RuntimeException("remote call failed:  setStreamProperties", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String restartApp(String path, java.lang.String namespace, java.lang.String appId, java.lang.String progTypes) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_restartApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "restartApp", null, namespace,appId,progTypes);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_restartApp, e.toString());
			throw new RuntimeException("remote call failed:  restartApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String createApp(String path, java.lang.String namespace, java.lang.String appId, java.lang.String artifactName, java.lang.String artifactVersion, java.lang.String scope) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_createApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "createApp", null, namespace,appId,artifactName,artifactVersion,scope);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_createApp, e.toString());
			throw new RuntimeException("remote call failed:  createApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String createAppWithConfig(String path, java.lang.String namespace, java.lang.String appId, java.lang.String artifactName, java.lang.String artifactVersion, java.lang.String scope, java.lang.String appConfig) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_createAppWithConfig);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "createAppWithConfig", null, namespace,appId,artifactName,artifactVersion,scope,appConfig);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_createAppWithConfig, e.toString());
			throw new RuntimeException("remote call failed:  createAppWithConfig", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setDatasetProperties(String path, java.lang.String namespace, java.lang.String datasetName, java.lang.String datasetProperties) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setDatasetProperties);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setDatasetProperties", null, namespace,datasetName,datasetProperties);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setDatasetProperties, e.toString());
			throw new RuntimeException("remote call failed:  setDatasetProperties", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	
	public java.lang.String setStreamTTL(String path, java.lang.String namespace, java.lang.String streamName, int ttlSeconds) {
		EClass c = CdapPackage.eINSTANCE.getCdapCluster(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterOperationEnum.REMOTE_setStreamTTL);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath(path, c, "setStreamTTL", null, namespace,streamName,ttlSeconds);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterMessageEnum.REMOTE_setStreamTTL, e.toString());
			throw new RuntimeException("remote call failed:  setStreamTTL", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

}
